### ISSUE TITLE
About PA model

### ISSUE THREAD

**Issue by anfry15rudals** [bsc-quantic/fourier#1]
Hello.
I found that part of "circuit" function of PA model wrote like below.

state = np.dot(self.k_gate(p[:6]), state)
state = np.dot(self.A_gate(p[6:9]), state)
state = np.dot(self.A_gate(p[9:15]), state)
        
Is it intended? I think you used KAK decomposition but the code looks not.

**Comment by bertacasas** [comment]
Hi,
Indeed we use the Cartan decomposition of SU(4) and the third line of the code should contain a 'k_gate' instead of an 'A_gate'. Thanks for noticing it!
